Add layout option and style
meilisearch/vuepress-plugin-meilisearch pull request #146
Opened 2021-06-01 15:03 UTC by mdubus

## What's wrong ?

**Problem 1:** 

[docs-searchbar](https://github.com/meilisearch/docs-searchbar.js) provides an option to choose between 2 layouts : "simple" and "columns".
But the plugin `vuepress-plugin-meilisearch` doesn't provide access to this existing option.

**Problem 2:** 

After making this option available, the design looks horrific: 
![before simple layout](https://user-images.githubusercontent.com/30866152/120343835-54c87280-c2f9-11eb-8cb8-0748c3c1c4ff.png)

## What's inside this PR

This PR makes the `layout` option available.
It also adapts the style to match the existing one in docs-searchbar.

Style in `docs-searchbar` (simple layout): 
![reference docs searchbar](https://user-images.githubusercontent.com/30866152/120344347-caccd980-c2f9-11eb-8412-4837569338f7.png)

Style in `vuepress-plugin-meilisearch` after this PR (simple layout): 
![after simple layout](https://user-images.githubusercontent.com/30866152/120345811-1af86b80-c2fb-11eb-8119-c12529a2248f.png)

## How to test

Go to the file `playground/.vuepress/config.js` and add `"layout": "simple"` in the options:
![Capture d’écran 2021-06-01 à 16 55 06](https://user-images.githubusercontent.com/30866152/120344750-28f9bc80-c2fa-11eb-9d65-7b1e8c8ff62c.png)

Note that you might need to restart your server.

Please make sure to test that it doesn't break the "columns" layout 🙏

2021-06-01 16:27 UTC, curquiza requested changes
LGTM except for one small change :)

2021-06-01 16:27 UTC, curquiza commented on README.md
> +        "layout": "simple"                      // Default: "columns"
```suggestion
        "cropLength": 50,                       // Default: 30
        "layout": "simple"                      // Default: "columns"
```

2021-06-02 11:35 UTC, bidoubiwa commented
bors merge

2021-06-02 11:36 UTC, bidoubiwa approved these changes

2021-06-02 12:23 UTC, bidoubiwa commented
bors merge

2021-06-02 12:37 UTC, bidoubiwa commented
bors r-

2021-06-02 13:15 UTC, curquiza approved these changes

2021-06-02 13:28 UTC, bidoubiwa commented
bors merge

2021-06-02 13:29 UTC, merged